var lessons = [
    {
        "id":101,
        "subject":"ENGLISH",
        "location":"BAUCHI",
        "price":280,
        "availableInventory":5,
        "image": "images/eng.jfif"
    },
    {
        "id":102,
        "subject":"MATHEMATICS",
        "location":"LAGOS",
        "price":215,
        "availableInventory":5,
        "image":"images/maths.jfif"   
    },
    {
        "id":103,
        "subject":"CHEMISTRY",
        "location":"ABUJA",
        "price":230,
        "availableInventory":5,
        "image":"images/chem.jfif"   
    },
    {
        "id":104,
        "subject":"PHYSICS",
        "location":"KWARA",
        "price":110,
        "availableInventory":5,
        "image":"images/physics.jfif"   
    },
    {
        "id":105,
        "subject":"ARABIC",
        "location":"SOKOTO",
        "price":150,
        "availableInventory":5,
        "image":"images/arabic.jfif"   
    },
    {
        "id":106,
        "subject":"ECONOMICS",
        "location":"KANO",
        "price":200,
        "availableInventory":5,
        "image":"images/econs.jfif"   
    },
    {
        "id":107,
        "subject":"MUSIC",
        "location":"OSUN",
        "price":110,
        "availableInventory":5,
        "image":"images/music.jfif"   
    },
    {
        "id":108,
        "subject":"PROGRAMMING",
        "location":"OGUN",
        "price":120,
        "availableInventory":5,
        "image":"images/programming.jfif"   
    },
    {
        "id":109,
        "subject":"AGRIC SCIENCE",
        "location":"KATSINA",
        "price":180,
        "availableInventory":5,
        "image":"images/agric.jfif"   
    },
    {
        "id":110,
        "subject":"SOCIAL STUDIES",
        "location":"KADUNA",
        "price":100,
        "availableInventory":5,
        "image":"images/social.jfif"   
    }
]